### ISSUE TITLE
能支持下nacos server开启auth后配置用户名密吗

### ISSUE THREAD

**Issue by junboXiang** [zhwaaaaaa/nginx-nacos-upstream#10]

**Comment by zhwaaaaaa** [comment]
https://github.com/zhwaaaaaa/nginx-nacos-upstream?tab=readme-ov-file#username-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%B2%A1%E5%BC%80%E5%90%AF-auth-%E4%B8%8D%E9%9C%80%E8%A6%81
