### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by lihuikun** [zhwaaaaaa/nginx-nacos-upstream#4]
表示看不懂实际的流程，可以写一下具体的操作流程？是下载nginx官方的包，然后将你的module放进去编译？

**Comment by lihuikun** [comment]
参数也是看不懂use_nacos_address data_id=cc group=aaa;这是啥意思？能不能具体一点，哪怕随便写一个ip地址都可以

**Comment by zhwaaaaaa** [comment]
> 表示看不懂实际的流程，可以写一下具体的操作流程？是下载nginx官方的包，然后将你的module放进去编译？
如何 编译 nginx 请参考 nginx 的官方文档。本项目已经包含nginx 源码，编译的命令是，
```
./configure --add-module=modules/auxiliary --add-module=modules/nacos && make && make install
```

**Comment by zhwaaaaaa** [comment]
> 参数也是看不懂use_nacos_address data_id=cc group=aaa;这是啥意思？能不能具体一点，哪怕随便写一个ip地址都可以

use_nacos_address 是 nacos 模块新加的配置，至于 data_id 和 group 代表什么请参考 nacos 官方文档。

**Comment by lik0914** [comment]
这个 NGINX 版本是有强制要求吗

**Comment by zhwaaaaaa** [comment]
> 这个 NGINX 版本是有强制要求吗

本项目已经包含nginx  1.20.2 的源码，并且对 nginx 源码 有轻微改动。目的是增加 一个新的 nginx 进程用于订阅 nacos，原来的nginx 设计不支持。

**Comment by zhushiyang** [comment]
> 

后面考虑独立出来吗？大部分公司对nginx的版本有要求。

**Comment by zhwaaaaaa** [comment]
> > 
> 
> 后面考虑独立出来吗？大部分公司对nginx的版本有要求。

不太好独立出来，对 nginx 有少量修改。

**Comment by hexw** [comment]
> > > 
> > 
> > 
> > 后面考虑独立出来吗？大部分公司对nginx的版本有要求。
> 
> 不太好独立出来，对 nginx 有少量修改。

应该做成独立插件的形式的,这样绑定特定nginx 很难有人使用,对nginx 有修改的话可以使用patch -p1  这种方式,例如参考
https://github.com/yaoweibin/nginx_upstream_check_module
