### ISSUE TITLE
![image](https://user-images.githubusercontent.com/103627075/199382041-fc8c2d04-7b93-413d-8835-dd554fb71bf9.png)

### ISSUE THREAD

**Issue by JayL946** [zhwaaaaaa/nginx-nacos-upstream#6]
![image](https://user-images.githubusercontent.com/103627075/199382041-fc8c2d04-7b93-413d-8835-dd554fb71bf9.png)
我找了一个新环境重新git clone下来，make还是有报错，而且我对比了，报错与之前是一样的，而我去找到了您修改的源码，确认是用您新改的源码，能麻烦再帮忙指导看看吗？Thanks

_Originally posted by @JayL946 in https://github.com/zhwaaaaaa/nginx-nacos-upstream/issues/5#issuecomment-1299484999_

**Comment by zhwaaaaaa** [comment]
欧，sorry 漏了一个地方。ngx_nacos_data.c 146 行。 的 err 变成 0. 试试

**Comment by JayL946** [comment]
感谢，没报错了
![image](https://user-images.githubusercontent.com/103627075/199384720-9b426933-5e64-4e39-9a25-b52072701f23.png)
