### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zhuanjin** [zhwaaaaaa/nginx-nacos-upstream#9]
modules/nacos/ngx_nacos_grpc.c: In function ‘ngx_nacos_grpc_update_send_window’:
modules/nacos/ngx_nacos_grpc.c:1637:33: error: ‘t’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1637 |         st->non_block_bufs.tail = t;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~^~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1453: objs/addon/nacos/ngx_nacos_grpc.o] Error 1
make[1]: Leaving directory '/home/martin/nginx-nacos-upstream'
make: *** [Makefile:10: build] Error 2

**Comment by zhwaaaaaa** [comment]
gcc 编译器 的 和 clang 在这里有点不兼容， clang 判断 了 这个case 是可以 实例化的， 使用 clang 编译器试试。 我在 下个版本 上 config 功能 的时候 会一起 修复 这个问题。

**Comment by zhwaaaaaa** [comment]
已经修复这个问题

**Comment by zhwaaaaaa** [comment]
已经可以通过 nginx 标准 方法编译 通过，这个我先 关了
